import { LevelInfo, Exercise, Workout, WorkoutScheduleDay } from '../../types';

export const DEFAULT_LEVELS: LevelInfo[] = [
  {
    id: 'basico',
    name: 'Básico',
    order: 1,
    badge: 'Nível 1',
    description: 'Fundamentos corporais, sustentação isométrica e variações adaptadas para construir base.',
    idealFor: 'Quem nunca treinou ou está recomeçando do zero absoluto.',
  },
  {
    id: 'iniciante',
    name: 'Iniciante',
    order: 2,
    badge: 'Nível 2',
    description: 'Flexões completas, remadas firmes, agachamentos livres e fortalecimento do core.',
    idealFor: 'Quem já tem controle básico e busca realizar as primeiras repetições completas.',
  },
  {
    id: 'pre_intermediario',
    name: 'Pré-intermediário',
    order: 3,
    badge: 'Nível 3',
    description: 'Barras fixas completas, paralelas (dips) e variações com maior alavanca corporal.',
    idealFor: 'Praticantes com força básica que querem consolidar barras e paralelas.',
  },
  {
    id: 'intermediario',
    name: 'Intermediário',
    order: 4,
    badge: 'Nível 4',
    description: 'Volume sólido de barras, flexões arqueiro, L-sit, paralelas profundas e controle de tronco.',
    idealFor: 'Atletas que dominam os movimentos fundamentais e buscam maestria e hipertrofia.',
  },
  {
    id: 'pre_avancado',
    name: 'Pré-avançado',
    order: 5,
    badge: 'Nível 5',
    description: 'Progressões de Muscle-Up, Handstand Push-up, Front Lever tuck e exercícios de alta potência.',
    idealFor: 'Quem busca habilidades avançadas e força isométrica e dinâmica de alto nível.',
  },
];

export const DEFAULT_EXERCISES: Exercise[] = [
  // Empurrar (Push)
  {
    id: 'ex_pushup_standard',
    name: 'Push Up',
    description: 'Flexão tradicional de solo com peitoral tocando o solo.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral, Tríceps, Deltoides',
    instruction: 'Apoie as mãos na largura dos ombros, pés unidos e corpo alinhado. Desça até tocar o peito no solo e suba estendendo totalmente os braços.',
    tips: ['Mantenha os cotovelos em ângulo de ~45 graus', 'Abdômen e glúteos firmemente contraídos'],
  },
  {
    id: 'ex_knee_pushup',
    name: 'Knee Push Up',
    description: 'Flexão com apoio nos joelhos para dosar carga e construir força inicial.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral, Tríceps, Deltoides',
    instruction: 'Apoie os joelhos no solo, mantenha o tronco alinhado da cabeça aos joelhos e execute a flexão completa.',
    tips: ['Não empine o quadril', 'Toque o peito próximo ao chão a cada repetição'],
  },
  {
    id: 'ex_bench_dips',
    name: 'Bench Dips',
    description: 'Mergulho de tríceps com mãos apoiadas em banco ou superfície estável.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Tríceps, Deltoide anterior, Peitoral',
    instruction: 'Apoie as mãos na borda do banco atrás das costas. Flexione os cotovelos até 90 graus e empurre para cima até a extensão completa.',
    tips: ['Mantenha as costas próximas à borda do banco', 'Ombros longe das orelhas'],
  },
  {
    id: 'ex_decline_pushup_adv_hold',
    name: 'Decline Push Up Advanced Hold',
    description: 'Sustentação isométrica avançada em posição de flexão declinada com pés elevados.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Peitoral superior, Ombros, Core',
    instruction: 'Coloque os pés sobre um banco ou superfície elevada e sustente a posição de flexão intermediária/baixa de forma rígida.',
    tips: ['Trave o abdômen para impedir que a lombar curve', 'Mantenha os ombros ativos e estáveis'],
  },
  {
    id: 'ex_dips_adv_hold',
    name: 'Dips Advanced Hold',
    description: 'Sustentação isométrica no apoio do mergulho em barras paralelas ou apoios fixos.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Tríceps, Peitoral, Ombros',
    instruction: 'Com os braços estendidos nas barras paralelas ou superfícies paralelas firmes, empurre o apoio para baixo e sustente o corpo no ar.',
    tips: ['Depressão escapular ativa: empurre os ombros para baixo', 'Mantenha o peito aberto e tronco firme'],
  },
  {
    id: 'ex_pike_hold',
    name: 'Pike Hold',
    description: 'Sustentação isométrica em V invertido para construção de força de ombros e trapézios.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Deltoides, Trapézio, Core',
    instruction: 'Posicione as mãos no chão e erga o quadril formando um V invertido. Mantenha os braços estendidos transferindo o peso corporal para os ombros.',
    tips: ['Olhe para os pés, mantendo o pescoço neutro', 'Empurre o chão continuamente'],
  },
  {
    id: 'ex_incline_pushup',
    name: 'Incline Push Up',
    description: 'Flexão com mãos elevadas em banco para alívio de peso corporal.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral inferior, Tríceps',
    instruction: 'Apoie as mãos em uma superfície elevada com o corpo em linha reta e desça o peito até a borda.',
    tips: ['Quanto mais alto o apoio, menor o peso corporal exigido'],
  },
  {
    id: 'ex_pushup_hold',
    name: 'Push Up Hold',
    description: 'Sustentação isométrica na metade da descida da flexão.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Peito, Ombros, Core',
    instruction: 'Segure a posição de flexão na metade da descida mantendo a postura firme.',
    tips: ['Respire com controle sem soltar a tensão no abdômen'],
  },
  {
    id: 'ex_decline_pushup_hold',
    name: 'Decline Push Up Hold',
    description: 'Sustentação isométrica com pés elevados.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Peitoral superior, Ombros',
    instruction: 'Coloque os pés em um degrau e segure a posição de prancha alta.',
    tips: ['Mantenha os glúteos apertados'],
  },
  {
    id: 'ex_dips_hold',
    name: 'Dips Hold',
    description: 'Sustentação isométrica nas barras paralelas.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Tríceps, Peitoral',
    instruction: 'Braços estendidos nas paralelas, empurre o chão para baixo.',
    tips: ['Ombros longe das orelhas'],
  },
  {
    id: 'ex_parallel_dips',
    name: 'Parallel Bar Dips (Paralelas)',
    description: 'Mergulho em barras paralelas com peso corporal completo.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral inferior, Tríceps, Deltoide frontal',
    instruction: 'Desça flexionando os braços até 90 graus e empurre de volta com força.',
    tips: ['Incline o tronco levemente à frente'],
  },
  {
    id: 'ex_diamond_pushup',
    name: 'Diamond Push Up',
    description: 'Flexão diamante com mãos unidas.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Tríceps, Peitoral medial',
    instruction: 'Polegares e indicadores juntos abaixo do peito, flexione com controle.',
    tips: ['Mantenha os cotovelos próximos ao corpo'],
  },
  {
    id: 'ex_pike_pushup',
    name: 'Pike Push Up',
    description: 'Flexão em V invertido para ombros e tríceps.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides anterior/lateral, Trapézio, Tríceps',
    instruction: 'Com o corpo em formato de V invertido e quadril elevado, flexione os cotovelos direcionando a cabeça à frente das mãos.',
    tips: ['Olhe para os pés', 'Mantenha as pernas estendidas ou levemente flexionadas se faltar mobilidade'],
  },
  {
    id: 'ex_typewriter_pushup',
    name: 'Typewriter Push Up',
    description: 'Flexão máquina de escrever com deslizamento lateral do tronco próximo ao solo.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral, Tríceps, Deltoides, Serrátil',
    instruction: 'Desça na posição de flexão e deslize o tronco lateralmente para um lado e depois para o outro rente ao solo.',
    tips: ['4 repetições para cada lado (8 no total)', 'Mantenha o peito o mais baixo possível durante o deslizamento'],
  },
  {
    id: 'ex_decline_pushup',
    name: 'Decline Push Up',
    description: 'Flexão com os pés elevados em banco ou caixa para ênfase no peitoral superior e ombros.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral superior, Deltoide anterior, Tríceps',
    instruction: 'Apoie as pontas dos pés em uma elevação e as mãos no solo. Faça a flexão completa mantendo o corpo reto.',
    tips: ['Core rígido sem arquear a lombar', 'Cotovelos em 45 graus'],
  },
  {
    id: 'ex_wide_pushup',
    name: 'Wide Push Up',
    description: 'Flexão com pegada aberta para maior ativação e alongamento das fibras do peitoral.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral maior, Deltoide anterior',
    instruction: 'Posicione as mãos mais abertas que a largura dos ombros e realize a flexão com descida controlada.',
    tips: ['Não eleve os ombros em direção ao pescoço', 'Amplitude máxima de movimento'],
  },
  {
    id: 'ex_archer_pushup',
    name: 'Archer Push Up',
    description: 'Flexão arqueiro unilateral.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral unilateral, Tríceps',
    instruction: 'Desça sobre um braço enquanto o outro fica esticado para o lado.',
    tips: ['Alterne os lados com controle'],
  },
  {
    id: 'ex_wall_handstand_hold',
    name: 'Wall Handstand Hold',
    description: 'Parada de mão na parede com sustentação isométrica e alinhamento de ombros.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Ombros, Trapézios, Tríceps, Core',
    instruction: 'Apoie as mãos no solo e suba os pés na parede empurrando ativamente o solo pelos ombros.',
    tips: ['Corpo firme em linha reta e glúteos contraídos', 'Mantenha os braços completamente estendidos'],
  },
  {
    id: 'ex_planche_lean_hold',
    name: 'Planche Lean Hold',
    description: 'Inclinação frontal de prancha com ombros à frente dos punhos para base de prancha.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Deltoide anterior, Serrátil anterior, Bíceps distal, Core',
    instruction: 'Na posição de prancha com braços esticados e escápulas protraídas, incline o corpo à frente levando os ombros bem além da linha dos punhos.',
    tips: ['Mantenha os cotovelos 100% travados e bloqueados', 'Protração máxima das escápulas (arredonde a parte superior das costas)'],
  },
  {
    id: 'ex_pseudo_planche_pushup',
    name: 'Pseudo Planche Push Up',
    description: 'Flexão com mãos recuadas na linha da cintura e ombros projetados à frente.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides anteriores, Peitoral maior, Tríceps, Serrátil',
    instruction: 'Posicione as mãos na altura do abdômen/cintura com dedos virados para fora. Realize a flexão mantendo a inclinação anterior do tronco.',
    tips: ['Mantenha a inclinação para frente durante toda a repetição', 'Não deixe o quadril ceder'],
  },
  {
    id: 'ex_wall_handstand_pushup',
    name: 'Wall Handstand Push Up',
    description: 'Flexão de braço em parada de mão apoiado na parede.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides, Trapézio superior, Tríceps braquial, Core',
    instruction: 'Em parada de mão na parede, flexione os cotovelos controladamente até a cabeça tocar o solo levemente à frente das mãos e empurre até a extensão total.',
    tips: ['Cotovelos em ângulo de 45° em direção ao corpo, nunca abertos a 90°', 'Empurre forte no topo bloqueando os ombros'],
  },
  {
    id: 'ex_deep_wide_pushup',
    name: 'Deep Wide Push Up',
    description: 'Flexão aberta profunda com paralletes ou blocos para máxima amplitude de peitoral.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Peitoral maior, Deltoides anteriores',
    instruction: 'Com as mãos bem abertas sobre apoios/paralletes baixas, desça o peito abaixo do nível das mãos obtendo alongamento e contração profunda.',
    tips: ['Desça com controle absoluto sentindo o peitoral abrir', 'Empurre contraindo o centro do peito'],
  },

  // Puxar (Pull) & Braços
  {
    id: 'ex_negative_wide_pullup',
    name: 'Negative Wide Pull Up',
    description: 'Descida lenta e controlada na barra fixa com pegada aberta pronada.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Grande dorsal, Redondo maior, Trapézio, Bíceps',
    instruction: 'Salte até que o queixo passe da barra com pegada bem aberta e execute a descida em 3 a 5 segundos.',
    tips: ['Resista ativamente durante toda a descida', 'Mantenha as escápulas ativadas'],
  },
  {
    id: 'ex_wide_australian_pullup',
    name: 'Wide Australian Pull Up',
    description: 'Remada invertida australiana na barra baixa com pegada aberta.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Romboides, Deltoide posterior, Bíceps',
    instruction: 'Em uma barra baixa, segure com pegada aberta pronada e puxe o peito até a barra com o corpo alinhado.',
    tips: ['Aperte as escápulas no topo da remada', 'Mantenha o corpo como uma prancha'],
  },
  {
    id: 'ex_lower_back_raises',
    name: 'Lower Back Raises',
    description: 'Elevação de pernas/tronco no solo para fortalecimento lombar e paravertebrais.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Eretores da espinha (Lombar), Glúteos',
    instruction: 'Deitado de bruços no solo, eleve as pernas estendidas e tronco superior ativando a cadeia lombar.',
    tips: ['Movimento suave sem solavancos', 'Segure 1 segundo no ponto de pico'],
  },
  {
    id: 'ex_superman_crunches',
    name: 'Superman Crunches',
    description: 'Extensão de tronco e membros deitado em decúbito ventral (super-homem).',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Lombar, Glúteos, Trapézios médios/inferiores',
    instruction: 'Deitado de bruços com braços à frente, erga simultaneamente braços, peito e pernas com contração máxima.',
    tips: ['Olhe para o solo para proteger a cervical', 'Sustente o topo por 1 segundo'],
  },
  {
    id: 'ex_neutral_grip_pullup',
    name: 'Neutral Grip Pull Up',
    description: 'Barra fixa com pegada neutra (palmas viradas uma para a outra).',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Bíceps, Braquial, Braquiorradial, Dorsais',
    instruction: 'Segure nas barras paralelas neutras e puxe até o queixo ultrapassar as mãos.',
    tips: ['Muito favorável para cotovelos e ombros', 'Controle a fase excêntrica'],
  },
  {
    id: 'ex_wide_chinup',
    name: 'Wide Chin Up',
    description: 'Barra fixa com pegada supinada aberta para pico de ativação do bíceps e grande dorsal.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Bíceps braquial, Dorsais',
    instruction: 'Com as palmas voltadas para você em pegada mais aberta que os ombros, puxe até o queixo passar da barra.',
    tips: ['Foque a contração no pico dos bíceps', 'Evite balançar o corpo'],
  },
  {
    id: 'ex_negative_sphinx_pushup',
    name: 'Negative Sphinx Push Up',
    description: 'Extensão excêntrica de tríceps no solo com descida controlada dos antebraços.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Tríceps (cabeça longa e lateral), Core',
    instruction: 'Da posição de prancha alta de mãos, desça lentamente flexionando os cotovelos para trás até os antebraços tocarem o solo.',
    tips: ['Desça em 3 a 4 segundos controlados', 'Mantenha os cotovelos apontados para trás, sem abrir'],
  },

  // Puxar (Pull)
  {
    id: 'ex_chinup_standard',
    name: 'Chin Up',
    description: 'Barra fixa com pegada supinada (palmas voltadas para você).',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Bíceps, Dorsais, Antebraço',
    instruction: 'Segure na barra com pegada supinada na largura dos ombros. Puxe até o queixo ultrapassar a barra e retorne estendendo os braços.',
    tips: ['Amplitude completa sem balanceio de pernas', 'Concentre a força nos bíceps e dorsais'],
  },
  {
    id: 'ex_chinup_adv_hold',
    name: 'Chin Up Advanced Hold',
    description: 'Sustentação isométrica no ponto mais alto da barra fixa supinada.',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Bíceps, Dorsais, Trapézio',
    instruction: 'Suba até o queixo passar da barra com pegada supinada e trave a posição com o peito próximo à barra durante os segundos estipulados.',
    tips: ['Aperte as escápulas para trás e para baixo', 'Mantenha a respiração estável'],
  },
  {
    id: 'ex_pullup_adv_hold',
    name: 'Pull Up Advanced Hold',
    description: 'Sustentação isométrica no topo da barra com pegada pronada (palmas para frente).',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Dorsais, Ombros posteriores, Bíceps',
    instruction: 'Segure a barra com pegada pronada aberta, puxe até o queixo ficar acima da barra e sustente a contração máxima no topo.',
    tips: ['Peito aberto e cotovelos apontados para o chão', 'Abdômen contraído para evitar balanço'],
  },
  {
    id: 'ex_negative_pullup',
    name: 'Negative Pull Up',
    description: 'Descida excêntrica lenta e controlada na barra fixa com pegada pronada.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Bíceps, Antebraços',
    instruction: 'Salte até que o queixo passe da barra e execute a descida em velocidade controlada de 3 a 5 segundos até a extensão total.',
    tips: ['Resista à gravidade durante todo o trajeto', 'Evite descer de forma descontrolada'],
  },
  {
    id: 'ex_australian_pullup',
    name: 'Australian Pull Up',
    description: 'Remada australiana invertida com barra baixa ou paralelas baixas.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Romboides, Bíceps, Trapézio',
    instruction: 'Sob uma barra na altura do quadril, posicione o corpo inclinado reto com calcanhares no solo e puxe o peito até a barra.',
    tips: ['Mantenha o corpo como uma prancha reta', 'Aperte as escápulas no final do movimento'],
  },
  {
    id: 'ex_incline_chinup',
    name: 'Incline Chin Up',
    description: 'Remada inclinada invertida com pegada supinada dando ênfase aos flexores de cotovelo.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Bíceps, Dorsal, Trapézio médio',
    instruction: 'Em barra baixa, segure com palmas voltadas para o rosto e puxe a barra na direção do peito/queixo.',
    tips: ['Mantenha os cotovelos próximos ao tronco', 'Contraia o bíceps no pico da remada'],
  },
  {
    id: 'ex_negative_chinup',
    name: 'Negative Chin Up',
    description: 'Descida excêntrica na pegada supinada.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Bíceps, Dorsais',
    instruction: 'Salte até o topo e desça controladamente em 3 a 4 segundos.',
    tips: ['Controle constante'],
  },
  {
    id: 'ex_chinup_hold',
    name: 'Chin Up Hold',
    description: 'Sustentação isométrica na barra supinada.',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Bíceps, Dorsais',
    instruction: 'Segure o queixo acima da barra supinada.',
    tips: ['Cotovelos para trás'],
  },
  {
    id: 'ex_scapula_pullup',
    name: 'Scapula Pull Up',
    description: 'Ativação escapular na barra sem flexão de cotovelos.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Escápulas, Dorsal',
    instruction: 'Pendurado, puxe as escápulas para baixo erguendo o tronco.',
    tips: ['Braços esticados'],
  },
  {
    id: 'ex_pullup_hold',
    name: 'Pull Up Hold',
    description: 'Sustentação no topo da barra pronada.',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Dorsais, Bíceps',
    instruction: 'Mantenha o queixo acima da barra pronada.',
    tips: ['Ativação total de costas'],
  },
  {
    id: 'ex_pullup_standard',
    name: 'Pull Up Completa',
    description: 'Barra fixa com pegada pronada completa.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Bíceps, Ombros',
    instruction: 'Pendure-se e puxe até o queixo ultrapassar a barra.',
    tips: ['Sem impulsos de perna'],
  },
  {
    id: 'ex_tuck_front_lever_hold',
    name: 'Tuck Front Lever Hold',
    description: 'Sustentação isométrica de Front Lever com joelhos agrupados junto ao peito.',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Grande dorsal, Redondo maior, Core profundo, Antebraços',
    instruction: 'Pendurado na barra com braços retos, puxe a barra para baixo trazendo o corpo à horizontal com joelhos dobrados no peito.',
    tips: ['Braços 100% esticados sem flexionar cotovelos', 'Mantenha o tronco e quadril rigorosamente na linha horizontal'],
  },
  {
    id: 'ex_tuck_front_lever_raises',
    name: 'Tuck Front Lever Raises',
    description: 'Elevações dinâmicas de Front Lever tuck da suspensão vertical até a horizontal.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Serrátil, Core, Flexores do quadril',
    instruction: 'Da posição suspensa na barra com joelhos no peito, puxe a barra com braços esticados até o corpo atingir a horizontal e desça controlado.',
    tips: ['Subida explosiva e descida em 2 a 3 segundos', 'Não use impulso nem dobre os cotovelos'],
  },
  {
    id: 'ex_dragon_flag_hold',
    name: 'Dragon Flag Hold',
    description: 'Sustentação estática do corpo em linha reta apoiando apenas a parte superior dos ombros/costas no banco.',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Core anterior, Reto abdominal, Dorsais, Glúteos',
    instruction: 'Deitado em um banco firme, segure a borda atrás da cabeça e erga todo o tronco e pernas em linha reta, sustentando a posição.',
    tips: ['Corpo rígido como uma tábua sem dobrar a cintura', 'Ativação máxima de glúteos e abdômen'],
  },
  {
    id: 'ex_wide_pullup',
    name: 'Wide Pull Up',
    description: 'Barra fixa com pegada bem aberta para largura e ativação lateral das dorsais.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Grande dorsal (fibras externas), Redondo maior, Trapézio',
    instruction: 'Segure a barra com pegada pronada significativamente além dos ombros e puxe o peito em direção à barra.',
    tips: ['Puxe focando nos cotovelos indo para baixo e para trás', 'Controle completo na descida'],
  },
  {
    id: 'ex_traps_shrugs',
    name: 'Traps Shrugs (Encolhimento em Paralelas/Barra)',
    description: 'Elevação e depressão escapular para espessura e ativação de trapézios.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Trapézio superior e médio, Escápulas',
    instruction: 'Em suspensão na barra ou paralelas, realize encolhimento escapular elevando os ombros em direção às orelhas e segure no topo.',
    tips: ['Braços esticados o tempo todo', 'Segure 1 segundo no pico de contração'],
  },
  {
    id: 'ex_wide_face_pullup',
    name: 'Wide Face Pull Up',
    description: 'Remada alta invertida com pegada aberta direcionando a barra ao rosto/queixo.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Deltoides posteriores, Manguito rotador, Romboides, Trapézio',
    instruction: 'Em uma barra horizontal inclinada, puxe o corpo direcionando a barra em direção aos olhos/testa com cotovelos altos.',
    tips: ['Excelente para saúde do manguito e postura', 'Aperte as costas no topo'],
  },
  {
    id: 'ex_reverse_leg_raises',
    name: 'Reverse Leg Raises',
    description: 'Elevação reversa de pernas no solo ou banco para extensão lombar e glúteos.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Lombar, Eretores da espinha, Glúteo máximo, Isquiotibiais',
    instruction: 'De bruços em banco ou solo, mantenha o tronco apoiado e eleve ambas as pernas estendidas até contrair a cadeia posterior.',
    tips: ['Movimento controlado sem hiperestender a coluna bruscamente'],
  },

  // Muscle Up, Back Lever e Braços (Arms)
  {
    id: 'ex_skin_the_cat',
    name: 'Skin The Cat',
    description: 'Rotação completa de ombros de 360 graus na barra ou argolas com suspensão invertida.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Mobilidade/força de ombros, Dorsais, Bíceps distal, Core',
    instruction: 'Pendurado na barra, passe as pernas entre os braços girando para a posição de Back Lever invertido e retorne com força.',
    tips: ['Execute devagar e controlado', 'Excelente para mobilidade de ombros para o Back Lever'],
  },
  {
    id: 'ex_tuck_back_lever_hold',
    name: 'Tuck Back Lever Hold',
    description: 'Sustentação isométrica de costas para a barra com joelhos no peito e braços estendidos.',
    type: 'TIME',
    category: 'arms',
    muscleGroup: 'Bíceps, Deltoide anterior, Peitoral, Lombar, Core',
    instruction: 'Da posição invertida (Skin the Cat), desça o corpo até a horizontal de costas para o solo com joelhos dobrados no abdômen.',
    tips: ['Cotovelos bloqueados', 'Mantenha o quadril e os ombros nivelados na mesma linha'],
  },
  {
    id: 'ex_negative_muscle_up',
    name: 'Negative Muscle Up',
    description: 'Descida excêntrica lenta da posição acima da barra até a suspensão total.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Peitoral, Tríceps, Dorsais, Bíceps, Core',
    instruction: 'Suba acima da barra (com salto ou apoio) e realize a transição para baixo de forma ultracontrolada em 4 a 6 segundos.',
    tips: ['Foque a resistência no ponto crítico da transição sobre a barra'],
  },
  {
    id: 'ex_chest_high_pullup',
    name: 'Chest High Pull Up',
    description: 'Puxada explosiva na barra com peito/esterno alcançando a barra.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Dorsais, Bíceps, Deltoides, Potência escapular',
    instruction: 'Puxe na barra com máxima velocidade e potência até o esterno ou abdômen superior tocar a barra.',
    tips: ['Concentre a explosão no início do movimento', 'Base fundamental para destravar o Muscle Up'],
  },
  {
    id: 'ex_assisted_one_arm_chinup',
    name: 'Assisted One Arm Chin Up',
    description: 'Barra supinada unilateral com leve assistência da outra mão na fita/toalha ou pulso.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Bíceps unilateral, Braquial, Dorsal unilateral, Antebraço',
    instruction: 'Segure a barra com uma mão em pegada supinada e use a outra mão segurando uma toalha/fita mais baixa para assistência mínima.',
    tips: ['5 reps com cada braço', 'Use o mínimo de ajuda possível do braço de apoio'],
  },
  {
    id: 'ex_straight_bar_dips',
    name: 'Straight Bar Dips',
    description: 'Mergulho de tríceps e peitoral realizado diretamente em cima de uma única barra reta.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Tríceps, Peitoral inferior, Deltoides, Core',
    instruction: 'Apoiado acima da barra reta, incline o tronco à frente e desça até a barra tocar a parte inferior do peito, empurrando de volta.',
    tips: ['Incline as pernas levemente para frente para equilibrar o centro de massa', 'Finalize o movimento empurrando bem alto'],
  },
  {
    id: 'ex_sphinx_pushup',
    name: 'Sphinx Push Up',
    description: 'Extensão concêntrica e excêntrica de tríceps no solo apoiando antebraços e empurrando com as palmas.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Tríceps braquial (cabeça longa e medial), Core',
    instruction: 'Na posição de prancha de antebraços, empurre com as palmas das mãos estendendo os cotovelos simultaneamente.',
    tips: ['Ambos os cotovelos sobem e descem juntos sem assimetria', 'Core firme'],
  },

  // Core e Pernas (Legs & Core / ABS)
  {
    id: 'ex_lunges',
    name: 'Lunges (Passada / Avanço)',
    description: 'Avanço dinâmico ou alternado com passada profunda para quadríceps e glúteos.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Quadríceps, Glúteo máximo, Isquiotibiais, Panturrilhas',
    instruction: 'Dê um passo à frente flexionando ambos os joelhos até 90 graus, mantendo o tronco ereto e o joelho traseiro próximo ao chão.',
    tips: ['15 repetições com cada perna (30 no total por série)', 'Mantenha o calcanhar da frente firme no solo'],
  },
  {
    id: 'ex_sumo_squat',
    name: 'Sumo Squat',
    description: 'Agachamento com base bem aberta e pontas dos pés para fora para ênfase em adutores e glúteos.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Adutores da coxa, Glúteos, Quadríceps',
    instruction: 'Afaste os pés além da largura dos ombros com pontas a 45°. Desça o quadril mantendo o tronco ereto e joelhos alinhados aos pés.',
    tips: ['Desça até a linha paralela ou abaixo', 'Contraia os glúteos na subida'],
  },
  {
    id: 'ex_one_leg_hamstring_levers',
    name: 'One Leg Hamstring Levers',
    description: 'Elevação pélvica unilateral com apoio de um calcanhar para força de posteriores e glúteos.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Posteriores de coxa (Isquiotibiais), Glúteos, Lombar',
    instruction: 'Deitado de costas, apoie apenas um calcanhar no solo e eleve o quadril acionando a musculatura posterior da perna de apoio.',
    tips: ['10 repetições para cada perna', 'Pausa isométrica de 1 segundo no topo'],
  },
  {
    id: 'ex_90deg_leg_raises',
    name: '90° Leg Raises',
    description: 'Elevação de pernas estendidas na barra fixa até o ângulo reto (L-Hang).',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Reto abdominal, Flexores do quadril, Core',
    instruction: 'Pendurado na barra fixa, erga as pernas estendidas até ficarem paralelas ao chão (90 graus) e desça com controle.',
    tips: ['Mantenha as pernas esticadas e unidas', 'Evite usar embalo'],
  },
  {
    id: 'ex_oblique_knee_raises',
    name: 'Oblique Knee Raises',
    description: 'Elevação de joelhos oblíqua na barra fixa para fortalecimento dos oblíquos abdominais.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Oblíquos abdominais, Reto abdominal, Antebraço',
    instruction: 'Pendurado na barra, puxe os joelhos flexionados lateralmente em direção à costela/axila de cada lado.',
    tips: ['8 repetições para cada lado (16 no total por série)', 'Descida controlada sem pêndulo'],
  },
  {
    id: 'ex_hanging_human_flag',
    name: 'Hanging Human Flag (Hold)',
    description: 'Sustentação isométrica de bandeira humana em mastro ou barra vertical.',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Oblíquos, Grande dorsal, Deltoides, Serrátil, Quadríceps',
    instruction: 'Segure a barra vertical com uma mão empurrando abaixo e a outra puxando acima. Erga o corpo do solo sustentando a alavanca.',
    tips: ['5 segundos para cada lado', 'Braço de baixo empurra forte para travar a alavanca'],
  },
  {
    id: 'ex_windshield_wipers',
    name: 'Windshield Wipers (Limpador de Pára-brisa)',
    description: 'Rotação lateral de pernas estendidas suspenso na barra ou deitado no solo.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Oblíquos abdominais, Reto abdominal, Serrátil, Dorsais',
    instruction: 'Erga as pernas até a barra e faça giros controlados de um lado para o outro descrevendo um arco amplo.',
    tips: ['5 reps para cada lado (10 no total)', 'Mantenha as pernas esticadas e controle o retorno'],
  },
  {
    id: 'ex_assisted_pistol_squat',
    name: 'Assisted Pistol Squat',
    description: 'Agachamento unilateral em uma perna com assistência de apoio de mão ou fita.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Quadríceps unilateral, Glúteos, Tornozelos, Core',
    instruction: 'Em uma perna só com a outra estendida à frente, agache profundamente segurando levemente em uma coluna/poste para equilíbrio.',
    tips: ['6 repetições para cada perna', 'Calcanhar da perna de apoio colado no chão'],
  },
  {
    id: 'ex_bulgarian_squat',
    name: 'Bulgarian Split Squat',
    description: 'Agachamento búlgaro unilateral com o pé traseiro elevado em banco.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Quadríceps, Glúteo máximo, Posterior de coxa',
    instruction: 'Apoie o peito de um pé em um banco atrás e agache com a perna da frente até a coxa ficar paralela ao chão.',
    tips: ['10 repetições para cada perna', 'Mantenha o tronco alinhado e peito aberto'],
  },
  {
    id: 'ex_one_leg_calf_raises',
    name: 'One Leg Calf Raises',
    description: 'Elevação unilateral de panturrilha em degrau para amplitude e força máxima.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Panturrilhas (Gastrocnêmio e Sóleo unilateral)',
    instruction: 'Apoie a ponta de um pé em um degrau e realize a flexão plantar máxima e descida completa.',
    tips: ['15 repetições para cada perna', '1 segundo de pausa no topo da contração'],
  },
  {
    id: 'ex_full_leg_raises',
    name: 'Full Leg Raises (Toes to Bar)',
    description: 'Elevação completa de pernas na barra fixa até os pés tocarem a barra.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Reto abdominal, Flexores do quadril, Serrátil, Dorsais',
    instruction: 'Pendurado na barra, erga as pernas estendidas em arco até a ponta dos pés encostar na barra com controle.',
    tips: ['Sem balanço de pêndulo', 'Descida controlada em 2 segundos'],
  },
  {
    id: 'ex_squat',
    name: 'Squat',
    description: 'Agachamento livre com peso corporal e amplitude profunda.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Quadríceps, Glúteos, Posterior de coxa',
    instruction: 'Pés na largura dos ombros, projete o quadril para trás e flexione os joelhos até abaixo de 90 graus, mantendo o peito ereto.',
    tips: ['Calcanhares sempre colados no chão', 'Joelhos alinhados com a ponta dos pés'],
  },
  {
    id: 'ex_hamstring_levers',
    name: 'Hamstring Levers',
    description: 'Elevação pélvica / alavanca de calcanhar para ativação e força dos isquiotibiais.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Posteriores de coxa, Glúteos, Lombar',
    instruction: 'Deitado de costas, apoie os calcanhares no solo e eleve o quadril acionando a musculatura posterior da coxa e glúteos.',
    tips: ['Pause por 1 segundo no topo de cada repetição', 'Evite forçar a curvatura lombar'],
  },
  {
    id: 'ex_calf_raises',
    name: 'Calf Raises',
    description: 'Elevação de panturrilhas em pé com flexão plantar completa.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Gastrocnêmio, Sóleo (Panturrilhas)',
    instruction: 'Em pé, erga os calcanhares o mais alto possível até a ponta dos pés e desça lentamente.',
    tips: ['Pausa isométrica de 1 segundo no pico', 'Amplitude completa em cada repetição'],
  },
  {
    id: 'ex_hanging_knee_raises',
    name: 'Hanging Knee Raises',
    description: 'Elevação de joelhos suspenso na barra fixa para core e reto abdominal.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Reto abdominal, Flexores do quadril, Antebraço',
    instruction: 'Pendurado na barra, flexione e eleve os joelhos em direção ao peito com controle sem utilizar pêndulo.',
    tips: ['Controle rigoroso na fase de descida', 'Evite embalo com as pernas'],
  },
  {
    id: 'ex_legs_hold',
    name: 'Legs Hold',
    description: 'Sustentação isométrica com pernas estendidas a poucos centímetros do chão.',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Abdômen inferior, Core profundo, Flexores',
    instruction: 'Deitado de costas no solo, eleve as pernas esticadas a ~15-20cm do chão e sustente a posição estática.',
    tips: ['Mantenha a lombar colada no chão', 'Olhe para a ponta dos pés para ativar o abdômen'],
  },
  {
    id: 'ex_short_bridge',
    name: 'Short Bridge',
    description: 'Ponte curta isométrica de glúteos e estabilização de pelve e lombar.',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Glúteos, Isquiotibiais, Paravertebrais',
    instruction: 'Deitado de costas com joelhos dobrados e pés firmes no solo, eleve o quadril formando uma linha reta dos joelhos aos ombros e sustente.',
    tips: ['Aperte os glúteos ativamente durante toda a sustentação', 'Não jogue o peso no pescoço'],
  },
  {
    id: 'ex_lying_leg_raises',
    name: 'Lying Leg Raises',
    description: 'Elevação de pernas deitado.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Abdômen inferior',
    instruction: 'Deitado, suba e desça as pernas sem tocar o solo.',
    tips: ['Lombar firme no chão'],
  },
  {
    id: 'ex_plank',
    name: 'Plank (Prancha Abdominal)',
    description: 'Prancha frontal isométrica.',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Core completo',
    instruction: 'Apoie antebraços e pontas dos pés, corpo reto.',
    tips: ['Respire continuamente'],
  },
  {
    id: 'ex_hollow_body',
    name: 'Hollow Body Hold',
    description: 'Posição em canoa.',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Core profundo',
    instruction: 'De costas, erga ombros e pernas com lombar travada.',
    tips: ['Não dobre os joelhos'],
  },
  {
    id: 'ex_lsit_tuck_hold',
    name: 'Tuck L-Sit Hold',
    description: 'Sustentação em L tuck.',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Abdômen, Tríceps',
    instruction: 'Erga o quadril e joelhos do chão nas paralelas ou solo.',
    tips: ['Ombros para baixo'],
  },

  // EXERCÍCIOS ESPECÍFICOS - NÍVEL PRÉ-AVANÇADO (BARZ CLUB)
  // Planche e Handstand
  {
    id: 'ex_tuck_planche',
    name: 'Tuck Planche (Hold)',
    description: 'Sustentação isométrica de prancha com braços esticados e joelhos agrupados junto ao peito no ar.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Deltoides anteriores, Peitoral maior, Serrátil, Core, Bíceps distal',
    instruction: 'Nas paralelas ou solo, incline os ombros bem à frente dos punhos, trave os cotovelos e eleve os joelhos recolhidos ao peito sustentando todo o corpo no ar.',
    tips: ['Cotovelos 100% esticados e bloqueados', 'Protração escapular máxima'],
  },
  {
    id: 'ex_handstand_hold',
    name: 'Handstand (Parada de Mão Livre)',
    description: 'Sustentação isométrica de parada de mão livre no solo ou paralelas.',
    type: 'TIME',
    category: 'push',
    muscleGroup: 'Deltoides, Trapézios, Tríceps, Core, Antebraços',
    instruction: 'Chute para a parada de mão, empurre o solo ativamente pelos ombros e trave o abdômen e glúteos em linha reta.',
    tips: ['Controle o equilíbrio pelas pontas dos dedos e palmas', 'Corpo rígido e pés em ponta'],
  },
  {
    id: 'ex_bent_arm_planche_press',
    name: 'Bent Arm Planche Press',
    description: 'Empurrão de prancha partindo com braços flexionados até a extensão ou transição.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Tríceps, Peitoral, Deltoides anteriores, Core',
    instruction: 'Com o corpo sustentado na horizontal em alavanca de braços flexionados (90°), empurre estendendo os cotovelos e projetando o tronco.',
    tips: ['Mantenha as pernas juntas ou em straddle elevado', 'Controle constante de equilíbrio'],
  },
  {
    id: 'ex_chest_to_wall_hspu',
    name: 'Chest to Wall Handstand Push Up',
    description: 'Flexão em parada de mão de frente para a parede (peito virado para o muro) para alinhamento estrito.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides, Trapézio superior, Tríceps, Core',
    instruction: 'Em parada de mão com o peito próximo à parede, flexione os cotovelos descendo até o topo da cabeça tocar o solo e empurre forte até o bloqueio.',
    tips: ['Cotovelos apontando a 45 graus', 'Não afaste o tronco da parede em arco lombar'],
  },
  {
    id: 'ex_elevated_pike_to_planche_press',
    name: 'Elevated Pike to Planche Press',
    description: 'Transição dinâmica de pike com pés elevados em caixa/banco empurrando para posição de alavanca planche.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides anteriores, Serrátil anterior, Peitoral, Core',
    instruction: 'Pés apoiados em elevação e mãos no solo em pike. Projete os ombros para frente em alavanca planche e empurre de volta à posição de pike.',
    tips: ['Mantenha os cotovelos retos e escápulas protraídas', 'Desloque o peso para os ombros'],
  },
  {
    id: 'ex_wide_wall_hspu',
    name: 'Wide Wall Handstand Push Up',
    description: 'Flexão em parada de mão na parede com pegada bem aberta para ênfase máxima nos deltoides laterais e anteriores.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides (lateral e anterior), Tríceps, Trapézio',
    instruction: 'Com as mãos posicionadas bem abertas além da largura dos ombros na parede, desça com controle e empurre até a extensão.',
    tips: ['Descida controlada', 'Empurre ativamente pelo calcanhar das mãos'],
  },
  {
    id: 'ex_elevated_pseudo_planche_pushup',
    name: 'Elevated Pseudo Planche Push Up',
    description: 'Flexão pseudo planche com pés elevados em banco para aumento significativo de sobrecarga anterior.',
    type: 'REPETITIONS',
    category: 'push',
    muscleGroup: 'Deltoides anteriores, Peitoral maior, Tríceps, Serrátil',
    instruction: 'Pés elevados em banco/caixa e mãos posicionadas na linha da cintura com inclinação máxima para frente. Realize a flexão sem perder a alavanca.',
    tips: ['Ombros bem à frente dos punhos durante toda a repetição', 'Trave o core'],
  },

  // Front Lever
  {
    id: 'ex_straddle_front_lever_hold',
    name: 'Straddle Front Lever (Hold)',
    description: 'Sustentação isométrica de Front Lever com pernas abertas/afastadas (straddle) para redução de alavanca.',
    type: 'TIME',
    category: 'pull',
    muscleGroup: 'Grande dorsal, Redondo maior, Core anterior, Deltoide posterior, Bíceps',
    instruction: 'Pendurado na barra, puxe a barra para baixo com braços retos trazendo o corpo para a horizontal com as pernas bem abertas e estendidas.',
    tips: ['Braços 100% esticados sem flexionar cotovelos', 'Mantenha o quadril nivelado na altura dos ombros'],
  },
  {
    id: 'ex_front_lever_raises',
    name: 'Front Lever Raises',
    description: 'Elevações completas de Front Lever da posição suspensa vertical até a horizontal ou acima da barra.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Romboides, Reto abdominal, Serrátil',
    instruction: 'Com braços estendidos, puxe a barra para baixo erguendo todo o corpo reto até a linha horizontal e desça com controle em 2 a 3 segundos.',
    tips: ['Sem dobrar os cotovelos nem dar impulso com as pernas', 'Descida excêntrica ultra controlada'],
  },
  {
    id: 'ex_inverted_row',
    name: 'Inverted Row (Remada Invertida Horizontal)',
    description: 'Remada invertida estrita na barra com corpo totalmente alinhado na horizontal.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Romboides, Trapézio médio, Deltoide posterior, Bíceps',
    instruction: 'Sob a barra, segure com pegada pronada e pés apoiados no solo ou elevação, puxando o peito até tocar a barra com força escapular.',
    tips: ['Aperte as escápulas no topo', 'Mantenha o tronco reto como uma tábua'],
  },
  {
    id: 'ex_upside_down_deadlift',
    name: 'Upside Down Deadlift',
    description: 'Extensão e elevação de tronco invertido na barra fixa simulando levantamento terra vertical.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Dorsais, Lombar, Glúteos, Isquiotibiais, Core',
    instruction: 'Na posição invertida (pernas para cima na barra), estenda e desça o quadril e pernas articulando pela lombar e dorsais com controle.',
    tips: ['Controle o movimento na fase de descida', 'Mantenha a pegada firme na barra'],
  },
  {
    id: 'ex_dragon_flag_raises',
    name: 'Dragon Flag Raises',
    description: 'Elevações dinâmicas de Dragon Flag no banco erguendo e descendo o corpo reto.',
    type: 'REPETITIONS',
    category: 'pull',
    muscleGroup: 'Reto abdominal, Oblíquos, Dorsais, Glúteos, Flexores do quadril',
    instruction: 'Apoiado nos ombros em um banco firme, erga o corpo reto até a vertical e desça até quase tocar o banco mantendo a rigidez total.',
    tips: ['Não dobre a cintura ou quadril', 'Descida lenta de 3 segundos'],
  },

  // Pistol Squat e Human Flag
  {
    id: 'ex_straddle_human_flag_hold',
    name: 'Straddle Human Flag (Hold)',
    description: 'Sustentação isométrica de bandeira humana em mastro com pernas afastadas (straddle).',
    type: 'TIME',
    category: 'legs_core',
    muscleGroup: 'Oblíquos abdominais, Dorsais, Deltoides, Serrátil, Quadríceps',
    instruction: 'Segure a barra vertical com uma mão empurrando abaixo e outra puxando acima. Erga o corpo à horizontal com pernas afastadas.',
    tips: ['5 segundos para cada lado', 'Trave o braço de baixo empurrando com força'],
  },
  {
    id: 'ex_negative_human_flag',
    name: 'Negative Human Flag',
    description: 'Descida excêntrica controlada da bandeira humana a partir da posição vertical superior.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Oblíquos, Grande dorsal, Deltoides, Core',
    instruction: 'Suba o corpo na vertical na barra e desça de forma lenta e resistida através da horizontal até o solo.',
    tips: ['5 reps para cada lado', 'Resista à gravidade no ponto horizontal'],
  },
  {
    id: 'ex_pistol_squat_unassisted',
    name: 'Pistol Squat (Livre)',
    description: 'Agachamento unilateral completo em uma perna sem nenhum apoio ou assistência.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Quadríceps unilateral, Glúteo máximo, Tornozelos, Core',
    instruction: 'Em uma perna com a outra estendida reta à frente, agache profundamente até o glúteo tocar o calcanhar e suba com força.',
    tips: ['6 repetições para cada perna', 'Mantenha o calcanhar colado no chão'],
  },
  {
    id: 'ex_shrimp_squat',
    name: 'Shrimp Squat (Agachamento Camarão)',
    description: 'Agachamento unilateral segurando o pé traseiro flexionado contra o glúteo.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Quadríceps, Glúteo médio e máximo, Equilíbrio',
    instruction: 'Fique em uma perna e segure o tornozelo da outra perna atrás com a mão. Agache até o joelho dobrado tocar levemente o solo e suba.',
    tips: ['6 repetições para cada perna', 'Mantenha o tronco firme e olhar à frente'],
  },
  {
    id: 'ex_elevated_hamstring_levers',
    name: 'Elevated Hamstring Levers',
    description: 'Elevação pélvica de calcanhares com pés elevados em banco ou caixa para extensão máxima de posteriores.',
    type: 'REPETITIONS',
    category: 'legs_core',
    muscleGroup: 'Isquiotibiais (Posteriores de coxa), Glúteo máximo, Lombar',
    instruction: 'Deitado de costas com calcanhares apoiados em um banco alto, eleve o quadril acionando a cadeia posterior com força.',
    tips: ['Mantenha a contração de 1 segundo no pico', 'Alinhe joelhos, quadril e ombros'],
  },

  // Muscle Up, Back Lever e One Arm Chin Up
  {
    id: 'ex_straddle_back_lever_hold',
    name: 'Straddle Back Lever (Hold)',
    description: 'Sustentação isométrica de costas para a barra com pernas estendidas e afastadas (straddle).',
    type: 'TIME',
    category: 'arms',
    muscleGroup: 'Bíceps distal, Deltoide anterior, Peitoral, Lombar, Core',
    instruction: 'Da posição invertida, desça o corpo de costas até a horizontal perfeita com pernas esticadas e afastadas em straddle.',
    tips: ['Cotovelos 100% travados e bloqueados', 'Mantenha a linha reta entre calcanhares e ombros'],
  },
  {
    id: 'ex_negative_back_lever',
    name: 'Negative Back Lever',
    description: 'Descida excêntrica da suspensão invertida até a linha horizontal do Back Lever.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Bíceps, Deltoides anteriores, Lombar, Peitoral',
    instruction: 'Da suspensão de cabeça para baixo, desça o corpo estendido de forma lenta em 4 a 5 segundos até a horizontal e retorne.',
    tips: ['Controle milimétrico da velocidade de descida', 'Braços esticados o tempo todo'],
  },
  {
    id: 'ex_one_arm_chinup_hold',
    name: 'One Arm Chin Up Hold',
    description: 'Sustentação isométrica unilateral na barra com queixo acima da barra sustentando o peso do corpo em um único braço.',
    type: 'TIME',
    category: 'arms',
    muscleGroup: 'Bíceps braquial unilateral, Braquiorradial, Dorsal, Antebraço',
    instruction: 'Suba com as duas mãos e solte uma das mãos, sustentando o corpo no topo com o queixo travado sobre a barra.',
    tips: ['5 segundos para cada braço', 'Aperte o bíceps e trave o ombro com depressão escapular'],
  },
  {
    id: 'ex_one_arm_negative_chinup',
    name: 'One Arm Negative Chin Up',
    description: 'Descida excêntrica unilateral lenta na barra fixa supinada com um único braço.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Bíceps unilateral, Dorsais, Manguito rotador, Antebraço',
    instruction: 'Suba com auxílio de ambas as mãos até o topo, solte um braço e realize a descida lenta de 4 a 6 segundos com um único braço.',
    tips: ['3 repetições para cada braço', 'Resista ao máximo em todo o percurso'],
  },
  {
    id: 'ex_muscle_up_complete',
    name: 'Muscle Up (Completo)',
    description: 'Subida explosiva na barra combinando puxada alta e transição direta para o mergulho acima da barra.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Dorsais, Peitoral, Tríceps, Bíceps, Deltoides, Core',
    instruction: 'Pendurado na barra, realize uma puxada explosiva arqueada até o peito, gire os punhos sobre a barra e empurre para a extensão total.',
    tips: ['Transição suave e simultânea com ambos os braços', 'Mantenha o core rígido'],
  },
  {
    id: 'ex_negative_false_grip_muscleup',
    name: 'Negative False Grip Muscle Up',
    description: 'Descida excêntrica de Muscle Up mantendo a pegada falsa (false grip) nos punhos.',
    type: 'REPETITIONS',
    category: 'arms',
    muscleGroup: 'Flexores do punho, Antebraço, Tríceps, Dorsais, Bíceps',
    instruction: 'Apoiado acima da barra com false grip, desça através da transição de mergulho até a suspensão completa em 4 a 6 segundos.',
    tips: ['Mantenha os punhos enrolados sobre a barra (false grip) durante toda a descida', 'Foco na transição lenta'],
  },
];

export const DEFAULT_WORKOUTS: Workout[] = [
  // NÍVEL BÁSICO
  {
    id: 'w_basico_push',
    levelId: 'basico',
    name: 'Treino de Empurrar Básico',
    description: 'Fortalecimento da cadeia anterior com flexões adaptadas e sustentações para base peitoral e de ombros.',
    category: 'push',
    estimatedMinutes: 25,
    exercises: [
      { id: 'we_b_p_1', workoutId: 'w_basico_push', exerciseId: 'ex_knee_pushup', order: 1, sets: 3, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_b_p_2', workoutId: 'w_basico_push', exerciseId: 'ex_incline_pushup', order: 2, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_b_p_3', workoutId: 'w_basico_push', exerciseId: 'ex_pushup_hold', order: 3, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_b_p_4', workoutId: 'w_basico_push', exerciseId: 'ex_decline_pushup_hold', order: 4, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_b_p_5', workoutId: 'w_basico_push', exerciseId: 'ex_dips_hold', order: 5, sets: 3, targetDuration: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_basico_pull',
    levelId: 'basico',
    name: 'Treino de Puxar Básico',
    description: 'Desenvolvimento inicial de força de pegada, dorsais e bíceps através de excêntricas e remadas.',
    category: 'pull',
    estimatedMinutes: 28,
    exercises: [
      { id: 'we_b_pl_1', workoutId: 'w_basico_pull', exerciseId: 'ex_negative_chinup', order: 1, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_b_pl_2', workoutId: 'w_basico_pull', exerciseId: 'ex_chinup_hold', order: 2, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_b_pl_3', workoutId: 'w_basico_pull', exerciseId: 'ex_scapula_pullup', order: 3, sets: 3, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_b_pl_4', workoutId: 'w_basico_pull', exerciseId: 'ex_pullup_hold', order: 4, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_b_pl_5', workoutId: 'w_basico_pull', exerciseId: 'ex_australian_pullup', order: 5, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_b_pl_6', workoutId: 'w_basico_pull', exerciseId: 'ex_incline_chinup', order: 6, sets: 3, targetRepetitions: 8, restDuration: 120 },
    ],
  },
  {
    id: 'w_basico_legs_core',
    levelId: 'basico',
    name: 'Core e Pernas Básico',
    description: 'Construção de base de membros inferiores e estabilização de tronco.',
    category: 'legs_core',
    estimatedMinutes: 26,
    exercises: [
      { id: 'we_b_lc_1', workoutId: 'w_basico_legs_core', exerciseId: 'ex_squat', order: 1, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_b_lc_2', workoutId: 'w_basico_legs_core', exerciseId: 'ex_hamstring_levers', order: 2, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_b_lc_3', workoutId: 'w_basico_legs_core', exerciseId: 'ex_calf_raises', order: 3, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_b_lc_4', workoutId: 'w_basico_legs_core', exerciseId: 'ex_lying_leg_raises', order: 4, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_b_lc_5', workoutId: 'w_basico_legs_core', exerciseId: 'ex_legs_hold', order: 5, sets: 3, targetDuration: 15, restDuration: 120 },
      { id: 'we_b_lc_6', workoutId: 'w_basico_legs_core', exerciseId: 'ex_plank', order: 6, sets: 3, targetDuration: 15, restDuration: 120 },
    ],
  },

  // NÍVEL INICIANTE (BARZ CLUB)
  {
    id: 'w_iniciante_push',
    levelId: 'iniciante',
    name: 'Treino de Empurrar Iniciante',
    description: 'Rotina oficial Barz Club: Push Up, Knee Push Up, Bench Dips e holds isométricos (Decline, Dips, Pike).',
    category: 'push',
    estimatedMinutes: 32,
    exercises: [
      { id: 'we_i_p_1', workoutId: 'w_iniciante_push', exerciseId: 'ex_pushup_standard', order: 1, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_i_p_2', workoutId: 'w_iniciante_push', exerciseId: 'ex_knee_pushup', order: 2, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_i_p_3', workoutId: 'w_iniciante_push', exerciseId: 'ex_bench_dips', order: 3, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_i_p_4', workoutId: 'w_iniciante_push', exerciseId: 'ex_decline_pushup_adv_hold', order: 4, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_i_p_5', workoutId: 'w_iniciante_push', exerciseId: 'ex_dips_adv_hold', order: 5, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_i_p_6', workoutId: 'w_iniciante_push', exerciseId: 'ex_pike_hold', order: 6, sets: 3, targetDuration: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_iniciante_pull',
    levelId: 'iniciante',
    name: 'Treino de Puxar Iniciante',
    description: 'Rotina oficial Barz Club: Chin Up, Holds de barra, Negativas controladas e Remadas Australianas/Inclinadas.',
    category: 'pull',
    estimatedMinutes: 32,
    exercises: [
      { id: 'we_i_pl_1', workoutId: 'w_iniciante_pull', exerciseId: 'ex_chinup_standard', order: 1, sets: 3, targetRepetitions: 4, restDuration: 120 },
      { id: 'we_i_pl_2', workoutId: 'w_iniciante_pull', exerciseId: 'ex_chinup_adv_hold', order: 2, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_i_pl_3', workoutId: 'w_iniciante_pull', exerciseId: 'ex_pullup_adv_hold', order: 3, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_i_pl_4', workoutId: 'w_iniciante_pull', exerciseId: 'ex_negative_pullup', order: 4, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_i_pl_5', workoutId: 'w_iniciante_pull', exerciseId: 'ex_australian_pullup', order: 5, sets: 3, targetRepetitions: 12, restDuration: 120 },
      { id: 'we_i_pl_6', workoutId: 'w_iniciante_pull', exerciseId: 'ex_incline_chinup', order: 6, sets: 3, targetRepetitions: 12, restDuration: 120 },
    ],
  },
  {
    id: 'w_iniciante_legs_core',
    levelId: 'iniciante',
    name: 'Core e Pernas Iniciante',
    description: 'Rotina oficial Barz Club: Squat, Hamstring Levers, Calf Raises, Hanging Knee Raises, Legs Hold e Short Bridge.',
    category: 'legs_core',
    estimatedMinutes: 32,
    exercises: [
      { id: 'we_i_lc_1', workoutId: 'w_iniciante_legs_core', exerciseId: 'ex_squat', order: 1, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_i_lc_2', workoutId: 'w_iniciante_legs_core', exerciseId: 'ex_hamstring_levers', order: 2, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_i_lc_3', workoutId: 'w_iniciante_legs_core', exerciseId: 'ex_calf_raises', order: 3, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_i_lc_4', workoutId: 'w_iniciante_legs_core', exerciseId: 'ex_hanging_knee_raises', order: 4, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_i_lc_5', workoutId: 'w_iniciante_legs_core', exerciseId: 'ex_legs_hold', order: 5, sets: 3, targetDuration: 30, restDuration: 120 },
      { id: 'we_i_lc_6', workoutId: 'w_iniciante_legs_core', exerciseId: 'ex_short_bridge', order: 6, sets: 3, targetDuration: 30, restDuration: 120 },
    ],
  },

  // NÍVEL PRÉ-INTERMEDIÁRIO (BARZ CLUB)
  {
    id: 'w_pre_inter_chest_shoulders',
    levelId: 'pre_intermediario',
    name: 'Peito e Ombros Pré-Intermediário',
    description: 'Rotina oficial Barz Club: Pike Push Up, Typewriter Push Up, Dips em paralelas, Decline Push Up, Wide Push Up e Push Up.',
    category: 'push',
    estimatedMinutes: 34,
    exercises: [
      { id: 'we_pi_cs_1', workoutId: 'w_pre_inter_chest_shoulders', exerciseId: 'ex_pike_pushup', order: 1, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_pi_cs_2', workoutId: 'w_pre_inter_chest_shoulders', exerciseId: 'ex_typewriter_pushup', order: 2, sets: 3, targetRepetitions: 4, restDuration: 120 },
      { id: 'we_pi_cs_3', workoutId: 'w_pre_inter_chest_shoulders', exerciseId: 'ex_parallel_dips', order: 3, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_pi_cs_4', workoutId: 'w_pre_inter_chest_shoulders', exerciseId: 'ex_decline_pushup', order: 4, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_pi_cs_5', workoutId: 'w_pre_inter_chest_shoulders', exerciseId: 'ex_wide_pushup', order: 5, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_pi_cs_6', workoutId: 'w_pre_inter_chest_shoulders', exerciseId: 'ex_pushup_standard', order: 6, sets: 3, targetRepetitions: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_pre_inter_back_lower',
    levelId: 'pre_intermediario',
    name: 'Costas e Lombar Pré-Intermediário',
    description: 'Rotina oficial Barz Club: Pull Up, Negative Wide Pull Up, Wide Australian Pull Up, Australian Pull Up, Lower Back Raises e Superman Crunches.',
    category: 'pull',
    estimatedMinutes: 34,
    exercises: [
      { id: 'we_pi_bl_1', workoutId: 'w_pre_inter_back_lower', exerciseId: 'ex_pullup_standard', order: 1, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_pi_bl_2', workoutId: 'w_pre_inter_back_lower', exerciseId: 'ex_negative_wide_pullup', order: 2, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_pi_bl_3', workoutId: 'w_pre_inter_back_lower', exerciseId: 'ex_wide_australian_pullup', order: 3, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_pi_bl_4', workoutId: 'w_pre_inter_back_lower', exerciseId: 'ex_australian_pullup', order: 4, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_pi_bl_5', workoutId: 'w_pre_inter_back_lower', exerciseId: 'ex_lower_back_raises', order: 5, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_pi_bl_6', workoutId: 'w_pre_inter_back_lower', exerciseId: 'ex_superman_crunches', order: 6, sets: 3, targetRepetitions: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_pre_inter_legs_abs',
    levelId: 'pre_intermediario',
    name: 'Pernas e Abs Pré-Intermediário',
    description: 'Rotina oficial Barz Club: Lunges, Sumo Squat, One Leg Hamstring Levers, Calf Raises, 90° Leg Raises e Oblique Knee Raises.',
    category: 'legs_core',
    estimatedMinutes: 34,
    exercises: [
      { id: 'we_pi_la_1', workoutId: 'w_pre_inter_legs_abs', exerciseId: 'ex_lunges', order: 1, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_pi_la_2', workoutId: 'w_pre_inter_legs_abs', exerciseId: 'ex_sumo_squat', order: 2, sets: 3, targetRepetitions: 20, restDuration: 120 },
      { id: 'we_pi_la_3', workoutId: 'w_pre_inter_legs_abs', exerciseId: 'ex_one_leg_hamstring_levers', order: 3, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_pi_la_4', workoutId: 'w_pre_inter_legs_abs', exerciseId: 'ex_calf_raises', order: 4, sets: 3, targetRepetitions: 20, restDuration: 120 },
      { id: 'we_pi_la_5', workoutId: 'w_pre_inter_legs_abs', exerciseId: 'ex_90deg_leg_raises', order: 5, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_pi_la_6', workoutId: 'w_pre_inter_legs_abs', exerciseId: 'ex_oblique_knee_raises', order: 6, sets: 3, targetRepetitions: 8, restDuration: 120 },
    ],
  },
  {
    id: 'w_pre_inter_biceps_triceps',
    levelId: 'pre_intermediario',
    name: 'Bíceps e Tríceps Pré-Intermediário',
    description: 'Rotina oficial Barz Club: Chin Up, Neutral Grip Pull Up, Wide Chin Up, Diamond Push Up, Bench Dips e Negative Sphinx Push Up.',
    category: 'arms',
    estimatedMinutes: 34,
    exercises: [
      { id: 'we_pi_bt_1', workoutId: 'w_pre_inter_biceps_triceps', exerciseId: 'ex_chinup_standard', order: 1, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_pi_bt_2', workoutId: 'w_pre_inter_biceps_triceps', exerciseId: 'ex_neutral_grip_pullup', order: 2, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_pi_bt_3', workoutId: 'w_pre_inter_biceps_triceps', exerciseId: 'ex_wide_chinup', order: 3, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_pi_bt_4', workoutId: 'w_pre_inter_biceps_triceps', exerciseId: 'ex_diamond_pushup', order: 4, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_pi_bt_5', workoutId: 'w_pre_inter_biceps_triceps', exerciseId: 'ex_bench_dips', order: 5, sets: 3, targetRepetitions: 12, restDuration: 120 },
      { id: 'we_pi_bt_6', workoutId: 'w_pre_inter_biceps_triceps', exerciseId: 'ex_negative_sphinx_pushup', order: 6, sets: 3, targetRepetitions: 8, restDuration: 120 },
    ],
  },

  // NÍVEL INTERMEDIÁRIO (BARZ CLUB)
  {
    id: 'w_inter_planche_handstand_push',
    levelId: 'intermediario',
    name: 'Planche, Handstand, Peito e Ombros',
    description: 'Rotina oficial Barz Club: Planche Lean Hold, Wall Handstand Hold, Pseudo Planche Push Up, Wall Handstand Push Up, Typewriter Push Up, Deep Wide Push Up, Decline Push Up e Dips.',
    category: 'push',
    estimatedMinutes: 38,
    exercises: [
      { id: 'we_in_php_1', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_planche_lean_hold', order: 1, sets: 5, targetDuration: 10, restDuration: 120 },
      { id: 'we_in_php_2', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_wall_handstand_hold', order: 2, sets: 5, targetDuration: 10, restDuration: 120 },
      { id: 'we_in_php_3', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_pseudo_planche_pushup', order: 3, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_in_php_4', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_wall_handstand_pushup', order: 4, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_in_php_5', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_typewriter_pushup', order: 5, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_in_php_6', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_deep_wide_pushup', order: 6, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_in_php_7', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_decline_pushup', order: 7, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_in_php_8', workoutId: 'w_inter_planche_handstand_push', exerciseId: 'ex_parallel_dips', order: 8, sets: 3, targetRepetitions: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_inter_frontlever_back_lower',
    levelId: 'intermediario',
    name: 'Front Lever, Costas e Lombar',
    description: 'Rotina oficial Barz Club: Tuck Front Lever Hold, Tuck Front Lever Raises, Scapula Pull Up, Dragon Flag Hold, Wide Pull Up, Traps Shrugs, Wide Face Pull Up e Reverse Leg Raises.',
    category: 'pull',
    estimatedMinutes: 38,
    exercises: [
      { id: 'we_in_fbl_1', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_tuck_front_lever_hold', order: 1, sets: 5, targetDuration: 10, restDuration: 120 },
      { id: 'we_in_fbl_2', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_tuck_front_lever_raises', order: 2, sets: 3, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_in_fbl_3', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_scapula_pullup', order: 3, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_in_fbl_4', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_dragon_flag_hold', order: 4, sets: 3, targetDuration: 10, restDuration: 120 },
      { id: 'we_in_fbl_5', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_wide_pullup', order: 5, sets: 3, targetRepetitions: 8, restDuration: 120 },
      { id: 'we_in_fbl_6', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_traps_shrugs', order: 6, sets: 3, targetRepetitions: 12, restDuration: 120 },
      { id: 'we_in_fbl_7', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_wide_face_pullup', order: 7, sets: 3, targetRepetitions: 12, restDuration: 120 },
      { id: 'we_in_fbl_8', workoutId: 'w_inter_frontlever_back_lower', exerciseId: 'ex_reverse_leg_raises', order: 8, sets: 3, targetRepetitions: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_inter_pistol_flag_legs_core',
    levelId: 'intermediario',
    name: 'Pistol Squat, Human Flag, Pernas e Core',
    description: 'Rotina oficial Barz Club: Hanging Human Flag, Windshield Wipers, Assisted Pistol Squat, Bulgarian Split Squat, Sumo Squat, One Leg Hamstring Lever, One Leg Calf Raises e Full Leg Raises.',
    category: 'legs_core',
    estimatedMinutes: 40,
    exercises: [
      { id: 'we_in_pflc_1', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_hanging_human_flag', order: 1, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_in_pflc_2', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_windshield_wipers', order: 2, sets: 3, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_in_pflc_3', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_assisted_pistol_squat', order: 3, sets: 5, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_in_pflc_4', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_bulgarian_squat', order: 4, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_in_pflc_5', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_sumo_squat', order: 5, sets: 3, targetRepetitions: 30, restDuration: 120 },
      { id: 'we_in_pflc_6', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_one_leg_hamstring_levers', order: 6, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_in_pflc_7', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_one_leg_calf_raises', order: 7, sets: 3, targetRepetitions: 15, restDuration: 120 },
      { id: 'we_in_pflc_8', workoutId: 'w_inter_pistol_flag_legs_core', exerciseId: 'ex_full_leg_raises', order: 8, sets: 3, targetRepetitions: 10, restDuration: 120 },
    ],
  },
  {
    id: 'w_inter_muscleup_backlever_arms',
    levelId: 'intermediario',
    name: 'Muscle Up, Back Lever, Bíceps e Tríceps',
    description: 'Rotina oficial Barz Club: Skin The Cat, Tuck Back Lever Hold, Negative Muscle Up, Chest High Pull Up, Assisted One Arm Chin Up, Wide Chin Up, Straight Bar Dips e Sphinx Push Up.',
    category: 'arms',
    estimatedMinutes: 40,
    exercises: [
      { id: 'we_in_muba_1', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_skin_the_cat', order: 1, sets: 3, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_in_muba_2', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_tuck_back_lever_hold', order: 2, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_in_muba_3', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_negative_muscle_up', order: 3, sets: 5, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_in_muba_4', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_chest_high_pullup', order: 4, sets: 3, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_in_muba_5', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_assisted_one_arm_chinup', order: 5, sets: 3, targetRepetitions: 5, restDuration: 120 },
      { id: 'we_in_muba_6', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_wide_chinup', order: 6, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_in_muba_7', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_straight_bar_dips', order: 7, sets: 3, targetRepetitions: 10, restDuration: 120 },
      { id: 'we_in_muba_8', workoutId: 'w_inter_muscleup_backlever_arms', exerciseId: 'ex_sphinx_pushup', order: 8, sets: 3, targetRepetitions: 10, restDuration: 120 },
    ],
  },

  // NÍVEL PRÉ-AVANÇADO (BARZ CLUB)
  {
    id: 'w_pre_avancado_planche_handstand',
    levelId: 'pre_avancado',
    name: 'Planche e Handstand',
    description: 'Rotina oficial Barz Club: Tuck Planche Hold, Handstand Hold, Bent Arm Planche Press, Chest to Wall Handstand Push Up, Elevated Pike to Planche Press, Wide Wall Handstand Push Up, Elevated Pseudo Planche Push Up, Dips e Push Up.',
    category: 'push',
    estimatedMinutes: 42,
    exercises: [
      { id: 'we_pa_ph_1', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_tuck_planche', order: 1, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_pa_ph_2', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_handstand_hold', order: 2, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_pa_ph_3', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_bent_arm_planche_press', order: 3, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_ph_4', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_chest_to_wall_hspu', order: 4, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_ph_5', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_elevated_pike_to_planche_press', order: 5, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_ph_6', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_wide_wall_hspu', order: 6, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_ph_7', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_elevated_pseudo_planche_pushup', order: 7, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_ph_8', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_parallel_dips', order: 8, sets: 4, targetRepetitions: 25, restDuration: 60 },
      { id: 'we_pa_ph_9', workoutId: 'w_pre_avancado_planche_handstand', exerciseId: 'ex_pushup_standard', order: 9, sets: 4, targetRepetitions: 25, restDuration: 60 },
    ],
  },
  {
    id: 'w_pre_avancado_front_lever',
    levelId: 'pre_avancado',
    name: 'Front Lever',
    description: 'Rotina oficial Barz Club: Straddle Front Lever Hold, Front Lever Raises, Scapula Pull Up, Inverted Row, Upside Down Deadlift, Dragon Flag Raises, Pull Up e Wide Face Pull Up.',
    category: 'pull',
    estimatedMinutes: 42,
    exercises: [
      { id: 'we_pa_fl_1', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_straddle_front_lever_hold', order: 1, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_pa_fl_2', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_front_lever_raises', order: 2, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_fl_3', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_scapula_pullup', order: 3, sets: 4, targetRepetitions: 8, restDuration: 60 },
      { id: 'we_pa_fl_4', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_inverted_row', order: 4, sets: 4, targetRepetitions: 8, restDuration: 60 },
      { id: 'we_pa_fl_5', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_upside_down_deadlift', order: 5, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_fl_6', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_dragon_flag_raises', order: 6, sets: 4, targetRepetitions: 8, restDuration: 60 },
      { id: 'we_pa_fl_7', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_pullup_standard', order: 7, sets: 4, targetRepetitions: 25, restDuration: 60 },
      { id: 'we_pa_fl_8', workoutId: 'w_pre_avancado_front_lever', exerciseId: 'ex_wide_face_pullup', order: 8, sets: 4, targetRepetitions: 25, restDuration: 60 },
    ],
  },
  {
    id: 'w_pre_avancado_human_flag_pistol',
    levelId: 'pre_avancado',
    name: 'Pistol Squat e Human Flag',
    description: 'Rotina oficial Barz Club: Straddle Human Flag Hold, Negative Human Flag, Pistol Squat, Shrimp Squat, Sumo Squat, Elevated Hamstring Levers, Calf Raises e Windshield Wipers.',
    category: 'legs_core',
    estimatedMinutes: 44,
    exercises: [
      { id: 'we_pa_hfp_1', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_straddle_human_flag_hold', order: 1, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_pa_hfp_2', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_negative_human_flag', order: 2, sets: 4, targetRepetitions: 5, restDuration: 60 },
      { id: 'we_pa_hfp_3', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_pistol_squat_unassisted', order: 3, sets: 5, targetRepetitions: 6, restDuration: 120 },
      { id: 'we_pa_hfp_4', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_shrimp_squat', order: 4, sets: 4, targetRepetitions: 6, restDuration: 60 },
      { id: 'we_pa_hfp_5', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_sumo_squat', order: 5, sets: 4, targetRepetitions: 30, restDuration: 60 },
      { id: 'we_pa_hfp_6', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_elevated_hamstring_levers', order: 6, sets: 4, targetRepetitions: 30, restDuration: 60 },
      { id: 'we_pa_hfp_7', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_calf_raises', order: 7, sets: 4, targetRepetitions: 30, restDuration: 60 },
      { id: 'we_pa_hfp_8', workoutId: 'w_pre_avancado_human_flag_pistol', exerciseId: 'ex_windshield_wipers', order: 8, sets: 5, targetRepetitions: 5, restDuration: 60 },
    ],
  },
  {
    id: 'w_pre_avancado_muscleup_backlever',
    levelId: 'pre_avancado',
    name: 'Back Lever, Muscle Up e One Arm Chin Up',
    description: 'Rotina oficial Barz Club: Straddle Back Lever Hold, Negative Back Lever, One Arm Chin Up Hold, One Arm Negative Chin Up, Muscle Up, Negative False Grip Muscle Up, Chin Up e Reverse Leg Raises.',
    category: 'arms',
    estimatedMinutes: 44,
    exercises: [
      { id: 'we_pa_mub_1', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_straddle_back_lever_hold', order: 1, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_pa_mub_2', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_negative_back_lever', order: 2, sets: 4, targetRepetitions: 3, restDuration: 60 },
      { id: 'we_pa_mub_3', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_one_arm_chinup_hold', order: 3, sets: 5, targetDuration: 5, restDuration: 120 },
      { id: 'we_pa_mub_4', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_one_arm_negative_chinup', order: 4, sets: 4, targetRepetitions: 3, restDuration: 60 },
      { id: 'we_pa_mub_5', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_muscle_up_complete', order: 5, sets: 5, targetRepetitions: 3, restDuration: 120 },
      { id: 'we_pa_mub_6', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_negative_false_grip_muscleup', order: 6, sets: 4, targetRepetitions: 5, restDuration: 60 },
      { id: 'we_pa_mub_7', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_chinup_standard', order: 7, sets: 4, targetRepetitions: 25, restDuration: 60 },
      { id: 'we_pa_mub_8', workoutId: 'w_pre_avancado_muscleup_backlever', exerciseId: 'ex_reverse_leg_raises', order: 8, sets: 5, targetRepetitions: 10, restDuration: 60 },
    ],
  },
];

// Helper to generate standard 8-day suggested schedule for each level
export const generateDefaultSchedule = (levelId: LevelInfo['id'], pushId: string, pullId: string, legsId: string): WorkoutScheduleDay[] => {
  return [
    { id: `sch_${levelId}_1`, levelId, dayNumber: 1, workoutId: pushId, isRestDay: false, order: 1 },
    { id: `sch_${levelId}_2`, levelId, dayNumber: 2, workoutId: pullId, isRestDay: false, order: 2 },
    { id: `sch_${levelId}_3`, levelId, dayNumber: 3, workoutId: legsId, isRestDay: false, order: 3 },
    { id: `sch_${levelId}_4`, levelId, dayNumber: 4, workoutId: null, isRestDay: true, order: 4 },
    { id: `sch_${levelId}_5`, levelId, dayNumber: 5, workoutId: pushId, isRestDay: false, order: 5 },
    { id: `sch_${levelId}_6`, levelId, dayNumber: 6, workoutId: pullId, isRestDay: false, order: 6 },
    { id: `sch_${levelId}_7`, levelId, dayNumber: 7, workoutId: legsId, isRestDay: false, order: 7 },
    { id: `sch_${levelId}_8`, levelId, dayNumber: 8, workoutId: null, isRestDay: true, order: 8 },
  ];
};

export const DEFAULT_SCHEDULES: Record<LevelInfo['id'], WorkoutScheduleDay[]> = {
  basico: generateDefaultSchedule('basico', 'w_basico_push', 'w_basico_pull', 'w_basico_legs_core'),
  iniciante: generateDefaultSchedule('iniciante', 'w_iniciante_push', 'w_iniciante_pull', 'w_iniciante_legs_core'),
  pre_intermediario: [
    { id: 'sch_pre_intermediario_1', levelId: 'pre_intermediario', dayNumber: 1, workoutId: 'w_pre_inter_chest_shoulders', isRestDay: false, order: 1 },
    { id: 'sch_pre_intermediario_2', levelId: 'pre_intermediario', dayNumber: 2, workoutId: 'w_pre_inter_back_lower', isRestDay: false, order: 2 },
    { id: 'sch_pre_intermediario_3', levelId: 'pre_intermediario', dayNumber: 3, workoutId: 'w_pre_inter_legs_abs', isRestDay: false, order: 3 },
    { id: 'sch_pre_intermediario_4', levelId: 'pre_intermediario', dayNumber: 4, workoutId: 'w_pre_inter_biceps_triceps', isRestDay: false, order: 4 },
    { id: 'sch_pre_intermediario_5', levelId: 'pre_intermediario', dayNumber: 5, workoutId: null, isRestDay: true, order: 5 },
    { id: 'sch_pre_intermediario_6', levelId: 'pre_intermediario', dayNumber: 6, workoutId: 'w_pre_inter_chest_shoulders', isRestDay: false, order: 6 },
    { id: 'sch_pre_intermediario_7', levelId: 'pre_intermediario', dayNumber: 7, workoutId: 'w_pre_inter_back_lower', isRestDay: false, order: 7 },
    { id: 'sch_pre_intermediario_8', levelId: 'pre_intermediario', dayNumber: 8, workoutId: 'w_pre_inter_legs_abs', isRestDay: false, order: 8 },
    { id: 'sch_pre_intermediario_9', levelId: 'pre_intermediario', dayNumber: 9, workoutId: 'w_pre_inter_biceps_triceps', isRestDay: false, order: 9 },
    { id: 'sch_pre_intermediario_10', levelId: 'pre_intermediario', dayNumber: 10, workoutId: null, isRestDay: true, order: 10 },
  ],
  intermediario: [
    { id: 'sch_intermediario_1', levelId: 'intermediario', dayNumber: 1, workoutId: 'w_inter_planche_handstand_push', isRestDay: false, order: 1 },
    { id: 'sch_intermediario_2', levelId: 'intermediario', dayNumber: 2, workoutId: 'w_inter_frontlever_back_lower', isRestDay: false, order: 2 },
    { id: 'sch_intermediario_3', levelId: 'intermediario', dayNumber: 3, workoutId: 'w_inter_pistol_flag_legs_core', isRestDay: false, order: 3 },
    { id: 'sch_intermediario_4', levelId: 'intermediario', dayNumber: 4, workoutId: 'w_inter_muscleup_backlever_arms', isRestDay: false, order: 4 },
    { id: 'sch_intermediario_5', levelId: 'intermediario', dayNumber: 5, workoutId: null, isRestDay: true, order: 5 },
    { id: 'sch_intermediario_6', levelId: 'intermediario', dayNumber: 6, workoutId: 'w_inter_planche_handstand_push', isRestDay: false, order: 6 },
    { id: 'sch_intermediario_7', levelId: 'intermediario', dayNumber: 7, workoutId: 'w_inter_frontlever_back_lower', isRestDay: false, order: 7 },
    { id: 'sch_intermediario_8', levelId: 'intermediario', dayNumber: 8, workoutId: 'w_inter_pistol_flag_legs_core', isRestDay: false, order: 8 },
    { id: 'sch_intermediario_9', levelId: 'intermediario', dayNumber: 9, workoutId: 'w_inter_muscleup_backlever_arms', isRestDay: false, order: 9 },
    { id: 'sch_intermediario_10', levelId: 'intermediario', dayNumber: 10, workoutId: null, isRestDay: true, order: 10 },
  ],
  pre_avancado: [
    { id: 'sch_pre_avancado_1', levelId: 'pre_avancado', dayNumber: 1, workoutId: 'w_pre_avancado_planche_handstand', isRestDay: false, order: 1 },
    { id: 'sch_pre_avancado_2', levelId: 'pre_avancado', dayNumber: 2, workoutId: 'w_pre_avancado_front_lever', isRestDay: false, order: 2 },
    { id: 'sch_pre_avancado_3', levelId: 'pre_avancado', dayNumber: 3, workoutId: 'w_pre_avancado_human_flag_pistol', isRestDay: false, order: 3 },
    { id: 'sch_pre_avancado_4', levelId: 'pre_avancado', dayNumber: 4, workoutId: 'w_pre_avancado_muscleup_backlever', isRestDay: false, order: 4 },
    { id: 'sch_pre_avancado_5', levelId: 'pre_avancado', dayNumber: 5, workoutId: null, isRestDay: true, order: 5 },
    { id: 'sch_pre_avancado_6', levelId: 'pre_avancado', dayNumber: 6, workoutId: 'w_pre_avancado_planche_handstand', isRestDay: false, order: 6 },
    { id: 'sch_pre_avancado_7', levelId: 'pre_avancado', dayNumber: 7, workoutId: 'w_pre_avancado_front_lever', isRestDay: false, order: 7 },
    { id: 'sch_pre_avancado_8', levelId: 'pre_avancado', dayNumber: 8, workoutId: 'w_pre_avancado_human_flag_pistol', isRestDay: false, order: 8 },
    { id: 'sch_pre_avancado_9', levelId: 'pre_avancado', dayNumber: 9, workoutId: 'w_pre_avancado_muscleup_backlever', isRestDay: false, order: 9 },
    { id: 'sch_pre_avancado_10', levelId: 'pre_avancado', dayNumber: 10, workoutId: null, isRestDay: true, order: 10 },
  ],
};
